version: '3'
services:
  database:
    image: "postgres:11.6"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/psql
      POSTGRES_DB: database_name
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: dbpassword
    ports:
      - 5432:5432
    expose:
      - 5432
volumes:
  db_data:
